server:
  port: 20022


spring:
  datasource:
    url: jdbc:mysql://139.199.98.207:5666/shenxiaoyu?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: shenxiaoyu
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info  
  
common:
  ylw:
    test: develop