server:
  port: 20022


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eladmin?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 11223344
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info  


common:
  ylw:
    test: test